### ISSUE TITLE
Invalid integer value

### ISSUE THREAD

**Issue by itsdeluxe** [xdenser/node-struct#19]
Using this hex value: **0x100000000000002** should print this integer to the console: **72057594037927938**

What I am seeing is this: **72057594037927940**

I have a few test cases, but this is the easiest to paste:
var idStruct = Struct().word64Ule('id');
idStruct.allocate();
idStruct.fields.id = 72057594037927938;

console.log( "id: " + idStruct.get('id') );

**Comment by xdenser** [comment]
It is Javascript VM limitation, not library issue.

http://stackoverflow.com/questions/9643626/javascript-cant-handle-64-bit-integers-can-it
