### ISSUE TITLE
Pass an array length from a field.

### ISSUE THREAD

**Issue by l0oky** [xdenser/node-struct#24]
Hello,

So I wanted to get an object (fields) from a buffer. I was wondering how do you pass already read field as the length of an array?

This is what I've tried but It doesn't work...
```javascript
  var PacketRecordsBodyOneBSegment = Struct()
      .word8('number_of_io'); // length of the following array ...
  var length = PacketRecordsBodyOneBSegment.fields.number_of_io;
  console.log('OneB length:', length); // undefined
  PacketRecordsBodyOneBSegment = PacketRecordsBodyOneBSegment
      .array('events', length, PacketRecordsBodyOneBio);
```

Ideally, something like this would be awesome, but I don't know how to implement it:

```javascript
  var PacketRecordsBodyOneBSegment = Struct()
      .word8('number_of_io'); // length of the following array ...
      .array('events', 'number_of_io', PacketRecordsBodyOneBio);
```

Thanks.

**Comment by l0oky** [comment]
I am maybe on to this to make a pull request.. But I need some help..

What does [this](https://github.com/xdenser/node-struct/blob/master/index.js#L314) `args` do?
And what is `priv.closures.push`, `p` and `p.len` ?

Thank you.

**Comment by l0oky** [comment]
I've tried to rewrite the arrayField.. This isn't working for some reason...

```javascript 
function arrayField(p, offset, len, type) {
    var as = Struct();
    var args = [].slice.call(arguments, 4);
    args.unshift(0);
    if(typeof len === 'string'){
      // Find the length priv
      len = as.get(len);
    }
    for (var i = 0; i < len; i++) {
        if (type instanceof Struct) {
            as.struct(i, type.clone());
        } else if (type in as) {
            args[0] = i;
            as[type].apply(as, args);
        }
    }
    this.length = as.length();
    this.offset = offset;
    this.allocate = function () {
        as._setBuff(p.buf.slice(offset, offset + as.length()));
    }
    this.get = function () {
        return as;
    }
    this.set = function (val) {
        as.set(val);
    }
}
```

**Comment by l0oky** [comment]
I also tried :
```javascript
  var PacketRecordsBodyOneBSegment = Struct()
      .word8('number_of_io'); // length of the following array ...
      .array('events', Struct().get('number_of_io'), PacketRecordsBodyOneBio);
```

**Comment by xdenser** [comment]
1. It is analog of C struct.  So it does not support structures of dynamic length. Allocate enough space to read whole array of PacketRecordsBodyOneBio or read it one by one - then you do not need PacketRecordsBodyOneBSegment.
2. From your code I do not see where you get data. You should either allocate buffer with `allocate` then you can write to structure, or set buffer with `_setBuffer` and read structured darta from buffer.

**Comment by l0oky** [comment]
I get my data from a buffer where I use _setBuff to analyze the buffer.
