### ISSUE TITLE
time_t variables

### ISSUE THREAD

**Issue by sjkelleyjr** [xdenser/node-struct#26]
I'm trying to use this library with a C struct that contains a few time_t variables.  Looking on my system they're 8 byte variables.  However, when I read with time_t variable any sort of word64 variable in your library the data after this read gets corrupted (I'm assuming this means I'm reading too much or too little data from the buffer).  I've also tried word32 and word16 variables with no luck (really just shooting in the dark at that point).

Do you have any suggestions for reading time_t variables? (I know it's a unique request)

**Comment by xdenser** [comment]
Array of 8 bytes. With 64 bit variable it is maybe precision problem. Array of 2 word32 should work. Byte order is important.

**Comment by xdenser** [comment]
Array of 8 bytes. With 64 bit variable it is maybe precision problem. Array of 2 word32 should work. Byte order is important.

**Comment by sjkelleyjr** [comment]
The array of 2 word32 appears to have worked.  For anyone who stumbles upon this, it looks like the second element of the word32 array contains the uint64_t (the epoch seconds) that the time_t struct contains.  I also had to keep an extra word32Ule to keep the rest of the struct aligned in memory.

**Comment by sjkelleyjr** [comment]
I lied, this is giving me the integer representation of the uint64_t cast in C.  I'm trying to get the long long version.  Apparently javascript has no native way of dealing with uint64 variables.  I think this may be the problem and not necessarily your library.

**Comment by sjkelleyjr** [comment]
Something absolutely bizarre is happening and I'm not sure if C or javascript is to blame.  In C the data looks like this E 4D A6 7C 59 in hex (this is incorrect, but not my portion of the code so it will be fixed somewhere else).  I'm reading in 3 8 byte arrays, with the extra 4 bytes discussed above.  The second 2 8 byte arrays look like this: E 0 0 0 59 7C A6 4D.  However, the first 8 byte array looks like this: 0 0 0 0 59 7C A6 4D.  Where is the missing E? its in the first byte of the 4 byte array.  Very odd, but at least now that I know what's happening I'm able to write an algorithm to solve this problem.

This can be closed if you have no further questions for me.

**Comment by sjkelleyjr** [comment]
Ok I deleted my previous comments so as to not confuse anyone.  The problem was there are 4 bytes being put in front of my three time_t structs.  If you read these out like so: 

.array('empty',4,'word8')

to get them out of the way before doing the reads, you should be able to read the time_t structs with simply word64Ule after that.
